"""
generate_triggers.py
--------------------
Connects to PostgreSQL, introspects all tables in `simpaisa_datasource` schema,
and generates sync trigger functions + trigger attachments for every table
targeting the `warehouse` schema.

Usage:
    pip install psycopg2-binary
    python generate_triggers.py

Output:
    - Prints SQL to stdout
    - Saves to `triggers_output.sql`
"""

import psycopg2
import os

# -----------------------------------------------
# CONFIG -- update these or use environment vars
# -----------------------------------------------
DB_CONFIG = {
    "host":     os.getenv("PG_HOST",  {HOST}),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "dbname":   os.getenv("PG_DB",    {Database}),
    "user":     os.getenv("PG_USER",     {Username}),
    "password": os.getenv("PG_PASSWORD", {Password}),
}

SOURCE_SCHEMA = "simpaisa_datasource"
TARGET_SCHEMA = "warehouse"
WHERE_CLAUSE  = '"dbId" = 8 AND "tran_id" = NEW."tran_id"'

# Columns to EXCLUDE from the UPDATE SET clause (PKs / auto-increments)
PK_COLUMNS = {"whId"}


# -----------------------------------------------
# INTROSPECTION
# -----------------------------------------------
def get_tables_and_columns(conn, schema):
    """Return {table_name: [col1, col2, ...]} for every table in schema."""
    query = """
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = %s
        ORDER BY table_name, ordinal_position
    """
    with conn.cursor() as cur:
        cur.execute(query, (schema,))
        rows = cur.fetchall()

    tables = {}
    for table, column in rows:
        tables.setdefault(table, []).append(column)
    return tables


# -----------------------------------------------
# SQL GENERATORS
# -----------------------------------------------
def generate_function(table, columns):
    func_name   = "sync_{}_to_warehouse".format(table)
    quoted_cols = ['"{}"'.format(c) for c in columns]
    new_vals    = ['NEW."{}"'.format(c) for c in columns]

    # UPDATE: exclude PK columns
    update_cols = [c for c in columns if c not in PK_COLUMNS]
    max_col_len = max(len('"{}"'.format(c)) for c in update_cols) if update_cols else 0

    # Aligned SET clause
    aligned_set = [
        '      "{col}"{pad} = NEW."{col}"'.format(
            col=c,
            pad=" " * (max_col_len - len('"{}"'.format(c)))
        )
        for c in update_cols
    ]

    col_list  = ",\n      ".join(quoted_cols)
    val_list  = ",\n      ".join(new_vals)
    set_block = ",\n".join(aligned_set)

    return """
-- ============================================================
-- TABLE: {source}.{table}
-- ============================================================
CREATE OR REPLACE FUNCTION {source}.{func_name}()
RETURNS TRIGGER AS $$
BEGIN

  -- INSERT operation
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO {target}.{table} (
      {col_list}
    )
    VALUES (
      {val_list}
    );

  -- UPDATE operation
  ELSIF (TG_OP = 'UPDATE') THEN
    UPDATE {target}.{table} SET
{set_block}
    WHERE {where};

  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""".format(
        source=SOURCE_SCHEMA,
        target=TARGET_SCHEMA,
        table=table,
        func_name=func_name,
        col_list=col_list,
        val_list=val_list,
        set_block=set_block,
        where=WHERE_CLAUSE,
    )


def generate_trigger(table):
    trigger_name = "trg_sync_{}".format(table)
    func_name    = "sync_{}_to_warehouse".format(table)
    return """
CREATE TRIGGER {trigger_name}
AFTER INSERT OR UPDATE
ON {source}.{table}
FOR EACH ROW
EXECUTE FUNCTION {source}.{func_name}();
""".format(
        trigger_name=trigger_name,
        source=SOURCE_SCHEMA,
        table=table,
        func_name=func_name,
    )


# -----------------------------------------------
# MAIN
# -----------------------------------------------
def main():
    print("Connecting to {}:{} / {} ...".format(
        DB_CONFIG["host"], DB_CONFIG["port"], DB_CONFIG["dbname"]
    ))

    conn = psycopg2.connect(**DB_CONFIG)
    tables = get_tables_and_columns(conn, SOURCE_SCHEMA)
    conn.close()

    if not tables:
        print("No tables found in schema '{}'. Check schema name / permissions.".format(SOURCE_SCHEMA))
        return

    print("Found {} table(s): {}\n".format(len(tables), ", ".join(tables.keys())))

    sql_parts = [
        "-- Auto-generated triggers: {} -> {}".format(SOURCE_SCHEMA, TARGET_SCHEMA),
        "-- Tables processed: {}".format(len(tables)),
        "-- Generated by generate_triggers.py\n",
    ]

    for table, columns in tables.items():
        sql_parts.append(generate_function(table, columns))
        sql_parts.append(generate_trigger(table))

    final_sql = "\n".join(sql_parts)

    # Write to file with UTF-8 encoding
    output_file = "triggers_output.sql"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(final_sql)

    print(final_sql)
    print("\nSQL saved to: {}".format(output_file))


if __name__ == "__main__":
    main()